name = "HDF5Channels"
uuid = "d41f482a-2007-4621-bcdb-489b75cae3ac"
authors = ["Mark Kittisopikul <markkitt@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
